### ISSUE TITLE
Add slide / slideshow hide and show display functions

### ISSUE THREAD

**Issue by klihelp** [okstaticzero/imagemax#3]
Hi,
I couldn't find a built-in way to hide the slide/slideshow and open it again.
This would be different from a destroy(), because data remain cached and just need to re-display if hidden.

**Comment by okstaticzero** [comment]
Hello,

You could set the galleries container to display:none using javascript/jQuery.

-Matt

On Sunday, February 16, 2014 10:34 AM, klihelp notifications@github.com wrote:

Hi,
I couldn't find a built-in way to hide the slide/slideshow and open it again.
This would be different from a destroy(), because data remain cached and just need to re-display if hidden.

**Comment by klihelp** [comment]
That's works for display only, but not working for attached functions and events. 
eg. slideshow mode continues to work and eat the cpu ...

**Comment by okstaticzero** [comment]
I see what you mean... Sorry but a method doesn't exist for that.
I'm very busy on other work so I'm not sure when I would be able to add that.

It is something someone who is familiar building plugins could add to the unminified code.

-Matt

On Tuesday, February 18, 2014 9:56 AM, klihelp notifications@github.com wrote:

That's works for display only, but not working for attached functions and events. 
eg. slideshow mode continues to work and eat the cpu ...
